project:
  type: website
  output-dir: docs

website:
  title: "LooperX-Scripting"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: sandstone
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem


