project:
  type: website
  output-dir: docs

website:
  title: "Schrödinger's Cat's Möbius 3 Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: docked
    contents: 
      - index.qmd
      - auto: "*.qmd"
    
format:
  html:
    theme: 
      light: sandstone
      dark: cyborg
    css: styles.css
    toc: false
    code-block-background: true
    code-copy: true
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 250px
      gutter-width: 1.5rem


